name       : stoken
version    : 0.91
release    : 2
source     :
    - https://github.com/cernekee/stoken/archive/v0.91.tar.gz : 5e5cce38e958de07b2d447d24e9564edaf566571b6fe04ce9099b5dc2dd3c0ac
license    : LGPL-2.1
component  : 
    - network.base
    - gui: network.util
summary    : 
    - stoken is a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens
    - gui: Graphical client for stoken, a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens
description:
    - stoken is a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens. The libstoken shared librairy can be use with openconnect
    - gui: Graphical client for stoken, a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hogweed)
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
patterns   :
    - gui:
      - /usr/bin/stoken-gui
      - /usr/share/applications
      - /usr/share/man/man1/stoken-gui.1
      - /usr/share/pixmaps
      - /usr/share/stoken
setup      : |
    %autogen --libdir=%libdir% --bindir=/usr/bin --disable-static
build      : |
    %make
install    : |
    %make_install
