name       : stoken
version    : 0.91
release    : 1
source     :
    - https://github.com/cernekee/stoken/archive/v0.91.tar.gz : 5e5cce38e958de07b2d447d24e9564edaf566571b6fe04ce9099b5dc2dd3c0ac
license    : LGPL-2.1
component  : network.base
summary    : stoken is a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens
description: |
    stoken is a tokencode generator compatible with RSA SecurID 128-bit (AES) tokens. The libstoken shared librairy can be use with openconnect
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
    - pkgconfig(hogweed)
setup      : |
    %autogen --libdir=%libdir% --bindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
